### ISSUE TITLE
i run make html ,and get worry

### ISSUE THREAD

**Issue by samping** [odoo/documentation-user#378]
my sphinx version is 
![image](https://user-images.githubusercontent.com/6119267/63207641-2796da00-c0fc-11e9-9b2d-b89c38740895.png)
and i run make html ,get worry
![image](https://user-images.githubusercontent.com/6119267/63207632-f5857800-c0fb-11e9-9ad6-81460a55f607.png)

**Comment by xmo-odoo** [comment]
Aye, I think we did not port odoo/odoo@2b28dd89b8b76761108391023a0cc51900c0a816 here so the "user" documentation currently isn't compatible with Sphinx 2.

In the meantime, use Sphinx 1.8

/cc @mart-e also @Julien00859 reported more / different errors so it's possible that Sphinx 2.2 further altered their API and we'd have some more changes to make.

**Comment by Julien00859** [comment]
Here is the complete output on my laptop.

Odoo v12, sphinx 1.8

    (odoo-venv) [12.0] ~/Projects/odoo-community/doc » ~/Projects/odoo-venv/bin/sphinx-build --version
    sphinx-build 1.8.5
    (odoo-venv) [12.0] ~/Projects/odoo-community/doc » make clean html
    rm -rf _build/*
    sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html
    WARNING: Could not lex literal_block as "xml+django". Highlighting skipped.
    WARNING: Could not lex literal_block as "xml". Highlighting skipped.
    WARNING: Could not lex literal_block as "xml". Highlighting skipped.

    Build finished. The HTML pages are in _build/html.

Odoo master, sphinx 1.8

    (odoo-venv) [master] ~/Projects/odoo-community/doc » make clean html    
    rm -rf _build/*
    sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html
    /home/julien/Projects/odoo-community/doc/reference/data.rst:252: WARNING: Error with CSV data in "csv-table" directive:
    ',' expected after '"'

    .. csv-table::
        :file: ../../odoo/addons/base/data/res.country.state.csv
        :header-rows: 1
        :class: table-striped table-hover table-condensed
    WARNING: missing attribute mentioned in :members: or __all__: module odoo.api, attribute 
    WARNING: Could not lex literal_block as "xml+django". Highlighting skipped.
    WARNING: Could not lex literal_block as "xml". Highlighting skipped.
    WARNING: Could not lex literal_block as "xml". Highlighting skipped.
    WARNING: Could not lex literal_block as "xml". Highlighting skipped.

    Build finished. The HTML pages are in _build/html.

Odoo master, sphinx 2.2

    (odoo-venv) [master] ~/Projects/odoo-community/doc » pip install -U sphinx
    Installing collected packages: sphinx
      Found existing installation: Sphinx 1.8.5
        Uninstalling Sphinx-1.8.5:
          Successfully uninstalled Sphinx-1.8.5
    Successfully installed sphinx-2.2.0
    (odoo-venv) [master] ~/Projects/odoo-community/doc » make clean html      
    rm -rf _build/*
    sphinx-build -b html -d _build/doctrees  -q -t solutions . _build/html
    /home/julien/Projects/odoo-community/doc/reference/data.rst:252: WARNING: Error with CSV data in "csv-table" directive:
    ',' expected after '"'

    .. csv-table::
        :file: ../../odoo/addons/base/data/res.country.state.csv
        :header-rows: 1
        :class: table-striped table-hover table-condensed
    WARNING: missing attribute mentioned in :members: or __all__: module odoo.api, attribute 

    Exception occurred:
      File "/home/julien/Projects/odoo-venv/lib/python3.6/site-packages/sphinx/ext/todo.py", line 290, in visit_todo_node
        if self.config.todo_include_todos:
    AttributeError: 'BootstrapTranslator' object has no attribute 'config'
    The full traceback has been saved in /tmp/sphinx-err-di_yyje6.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    Makefile:52: recipe for target 'html' failed
    make: *** [html] Error 2

As suggested, it works fine with `pip install -U 'sphinx==1.8.5'

**Comment by rim-odoo** [comment]
On my machine (ArchLinux)
```bash
~$ sphinx-build --version
sphinx-build 2.2.0
~$ sphinx-build2 --version
sphinx-build2 1.8.5
```
therefore I can force the version to the Makefile like this
```bash
make html SPHINXBUILD=sphinx-build2
```
